### PR TITLE
PR: Add find_git function to verify correctly if git is installed on macOS

### LINKED ISSUE #12045: Spyder prompts to install command line tools in macOS
### Issue Report Checklist

* [Y ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [Y] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [Y] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [Y ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [Y ] Tried basic troubleshooting (if a bug/error)
    * [Y ] Restarted Spyder
    * [Y ] Reset preferences with ``spyder --reset``
    * [Y ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [Y ] Tried the other applicable steps from the Troubleshooting Guide
* [Y ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Installed the new version of spyder today. Everytime i click to a different tab a prompt appears as which asks to install Xcode, saying git is a part of Command Line Developer Tools. plz see the image I have attached. 
Its really annoying and I dont want to install Xcode. What can be done to remove this prompt to appear?

### What steps reproduce the problem?

1. Installed the latest version of spyder, which removed a lot of packages which i reinstalled manually using pip install
2. opening two or more files as different tabs and clicking any of them causes this to appear

## Versions

* Spyder version: 4.1.1
* Python version: 3.7.0 64-bit
* Qt version: 5.12.7
* PyQt version: 5.12.3
* Operating System name/version: MacOs Mojave 10.14.6
Error

### PR DESCRIPTION
**Pull request by juanis2112**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

 Added find_git function for macOS to verify correctly if git is installed

### Issue(s) Resolved

Fixes #12045

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
Juanis2112

### CODE REVIEW

File: spyder/utils/check-git.sh [hunk 1]
```diff
@@ -0,0 +1,2 @@
+#!/usr/bin/env bash
+xcode_tools_dir=$(xcode-select -p 2>/dev/null) && ls ${xcode_tools_dir}/usr/bin/git
```
Comment (ccordoba12) [inline spyder/utils/check-git.sh:2]:
```suggestion

# This tests if git is properly installed in macOS computers.
# See docksal/docksal#1003 for the explanation.
xcode_tools_dir=$(xcode-select -p 2>/dev/null) && ls ${xcode_tools_dir}/usr/bin/git

```

File: spyder/utils/programs.py [hunk 2]
```diff
@@ -1005,3 +1008,14 @@ def is_spyder_process(pid):
         return any(conditions)
     except (psutil.NoSuchProcess, psutil.AccessDenied):
         return False
+
+
+def find_git():
```
Comment (ccordoba12) [inline spyder/utils/programs.py:1013]:
```suggestion
def find_git():
    """Find git executable in the system."""
```

**Review by ccordoba12 — COMMENTED** [review]
Thanks @juanis2112 for finding and implementing the solution to this problem! It looks pretty great!

I only left two small suggestions for you.

**Review by ccordoba12 — APPROVED** [review]
Great work @juanis2112!
